<?php
define("TITLE_STRING", "PiCam1 Voordeur");
define("IPCAM", "192.168.2.11");
define("VIDEO_DIR", "videos");
define("STILL_DIR", "stills");
define("TIMELAPSE_DIR", "/timelapse");
define("ARCHIVE_DIR", "archive");
define("N_VIDEO_SCROLL_PIXELS", "380");
define("N_STILL_SCROLL_PIXELS", "300");
define("N_THUMB_SCROLL_PIXELS", "770");
define("N_LOG_SCROLL_PIXELS", "770");
define("DEFAULT_TEXT_COLOR", "black");
define("SELECTED_TEXT_COLOR", "#500808");
define("MEDIA_TEXT_COLOR", "#0000EE");
define("MANUAL_VIDEO_TEXT_COLOR", "#085008");
define("LOG_TEXT_COLOR", "black");
define("VIDEO_URL", "");
define("NAME_STYLE", "short");
define("N_COLUMNS", "4");
define("VIDEOS_MODE", "thumbs");
define("ARCHIVE_INITIAL_VIEW", "videos");
define("ARCHIVE_THUMBS_SCROLLED", "yes");
define("MEDIA_THUMBS_SCROLLED", "yes");
define("CONFIG_EVENT_COUNT", "18");
$config_event_count = 18;
$n_columns = 4;
$name_style = "short";
$n_video_scroll_pixels = 380;
$n_still_scroll_pixels = 300;
$default_text_color = "black";
$selected_text_color = "#500808";
$media_text_color = "#0000EE";
$manual_video_text_color = "#085008";
$n_thumb_scroll_pixels = 770;
$n_log_scroll_pixels = 770;
$log_text_color = "black";
$background_image = "images/paper1.png";
$archive_initial_view = "thumbs";
$archive_thumbs_scrolled = "yes";
$media_thumbs_scrolled = "yes";
$videos_mode = "thumbs";
$video_url = "";
$include_control = "no";
if (defined('N_COLUMNS')) $n_columns = N_COLUMNS;
if (defined('NAME_STYLE')) $name_style = NAME_STYLE;
if (defined('N_VIDEO_SCROLL_PIXELS')) $n_video_scroll_pixels = N_VIDEO_SCROLL_PIXELS;
if (defined('N_STILL_SCROLL_PIXELS')) $n_still_scroll_pixels = N_STILL_SCROLL_PIXELS;
if (defined('DEFAULT_TEXT_COLOR')) $default_text_color = DEFAULT_TEXT_COLOR;
if (defined('SELECTED_TEXT_COLOR')) $selected_text_color = SELECTED_TEXT_COLOR;
if (defined('MEDIA_TEXT_COLOR')) $media_text_color = MEDIA_TEXT_COLOR;
if (defined('MANUAL_VIDEO_TEXT_COLOR')) $manual_video_text_color = MANUAL_VIDEO_TEXT_COLOR;
if (defined('VIDEOS_MODE')) $videos_mode = VIDEOS_MODE;
if (defined('ARCHIVE_INITIAL_VIEW')) $archive_initial_view = ARCHIVE_INITIAL_VIEW;
if (defined('ARCHIVE_THUMBS_SCROLLED')) $archive_thumbs_scrolled = ARCHIVE_THUMBS_SCROLLED;
if (defined('MEDIA_THUMBS_SCROLLED')) $media_thumbs_scrolled = MEDIA_THUMBS_SCROLLED;
if (defined('N_THUMB_SCROLL_PIXELS')) $n_thumb_scroll_pixels = N_THUMB_SCROLL_PIXELS;
if (defined('N_LOG_SCROLL_PIXELS')) $n_log_scroll_pixels = N_LOG_SCROLL_PIXELS;
if (defined('LOG_TEXT_COLOR')) $log_text_color = LOG_TEXT_COLOR;
if (defined('BACKGROUND_IMAGE')) $background_image = BACKGROUND_IMAGE;
if (defined('VIDEO_URL')) $video_url = VIDEO_URL;
if (defined('INCLUDE_CONTROL')) $include_control = INCLUDE_CONTROL;
if (defined('CONFIG_EVENT_COUNT')) $old_event_count = CONFIG_EVENT_COUNT;
else $old_event_count = $config_event_count;